### ISSUE TITLE
What is the contact email for a responsible disclosure of a security issue?

### ISSUE THREAD

**Issue by eranation** [openid/AppAuth-JS#102]
I found a (low severity probably) small security issue, what is the best contact to do a responsible disclosure? (low or not, it's still an issue, so I rather not just issue a pull request / describe it here in public)

I tried contacting the official OpenID contact details, but didn't hear back yet.

Again, it's probably a low impact issue, affecting only old browsers, easy to reproduce and easy to fix, but still it's security related so I rather follow the protocol.

**Comment by tikurahul** [comment]
Sorry am on vacation at the moment. Can you please reach out to me at rahulrav (at) google ?

**Comment by tikurahul** [comment]
Thanks for reporting the bug !
