### ISSUE TITLE
Couldn't connect to Discord

### ISSUE THREAD

**Issue by Djaymare** [openid/AppAuth-JS#106]
Hello ! It may be a noobish question, but I couldn't find any other sample than https://github.com/googlesamples/appauth-js-electron-sample. How would I connect to Discord ?

## Expected Behavior
Some Discord endpoint should return a json

## Describe the problem
Using the sample, I replaced openIdConnectUrl :
- with https://discordapp.com/api/oauth2/authorize but it returns a 404
- with https://discordapp.com/oauth2/authorize but it returns a HTML

How can I get the json ?

  * AppAuth-JS version: 1.2.2
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): Node v11.9.0, Electron 4.0.0, Angular 7.2.7

**Comment by tikurahul** [comment]
Take a look at: https://discordapp.com/developers/docs/topics/oauth2

You will need the authorization and token endpoints. In addition you will also need to sign up for a client_id.
