### ISSUE TITLE
Angular 7 / CLI Sample

### ISSUE THREAD

**Issue by craigbroadman** [openid/AppAuth-JS#108]
## Expected Behavior
This isn't so much of an issue, more of a question... Do you have a sample application written in Angular 7 / CLI or documentation that describes the steps I need to take to implement?

#### [REQUIRED] Describe expected behavior
I would like to build an Angular CLI application using this library, is there a sample for this use case available?

## Describe the problem
I cannot find an Angular 7 sample application.

#### [REQUIRED] Actual Behavior
n/a

#### [REQUIRED] Steps to reproduce the behavior
n/a

#### [REQUIRED] Environment
n/a

  * AppAuth-JS version: ________________
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): _______________________
  * Source code snippts (inline or JSBin)

**Comment by tikurahul** [comment]
The library has a couple of samples. You can take a look at https://github.com/openid/AppAuth-JS/blob/master/src/app/index.ts 

That should help you get started.
