### ISSUE TITLE
Add support for acr_values option for authorization requests

### ISSUE THREAD

**Issue by michaelkro** [openid/AppAuth-JS#110]
## Expected Behavior
Authorization requests accept `acr_values` as an optional parameter. [Open ID Spec](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)
#### [REQUIRED] Describe expected behavior
When initializing a new instance of `AuthorizationRequest`, it accepts `acr_values` as a valid option.

```js
new AuthorizationRequest({
  client_id: '<CLIENT_ID>',
  // ...
  acr_values: '<ACR_VALUES>'
})
```
## Describe the problem
It is not possible to pass the `acr_values` option as a parameter for authorization requests
#### [REQUIRED] Actual Behavior
The server returns a 500 error when authorization requests contain the `acr_values` option
#### [REQUIRED] Steps to reproduce the behavior
Add `acr_values` as a parameter when initializing an instance of `AuthorizationRequest`
#### [REQUIRED] Environment

  * AppAuth-JS version:  1.2.3
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): node/electron
  * Source code snippts (inline or JSBin)

**Comment by tikurahul** [comment]
You should be using `extras`. 

https://github.com/openid/AppAuth-JS/blob/master/src/authorization_request.ts#L28

**Comment by michaelkro** [comment]
ok, thanks for the quick response @tikurahul!

**Comment by michaelkro** [comment]
Confirm that this is the correct solution. Thanks again!
