### ISSUE TITLE
Don't include redirect_uri property when sending a refresh token request

### ISSUE THREAD

**Issue by aberasarte** [openid/AppAuth-JS#112]
## Expected Behavior
The `redirect_uri` shouldn't be sent in refresh token flows.

## Describe the problem
When asking for a new token using a `refresh_token`, it is mandatory to set a value for the `redirect_uri` property of the `TokenRequest` class. An example can be seen [here](https://github.com/openid/AppAuth-JS/blob/master/src/app/index.ts#L147).

According to the spec, the `redirect_uri` is not an expected property for this flow so it shouldn't been asked or sent. https://tools.ietf.org/html/rfc6749#section-6

**Comment by tikurahul** [comment]
Thanks for the bug report. Will have a fix.

**Comment by tikurahul** [comment]
Looking into this further. Looks like `redirect_uri` is not an expected property. However, the documentation listed at https://tools.ietf.org/html/rfc6749#section-4.1.3 actually uses the following example:

```
POST /token HTTP/1.1
Host: server.example.com
Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&code=SplxlOBeZQQYbYS6WxSbIA
&redirect_uri=https%3A%2F%2Fclient%2Eexample%2Ecom%2Fcb
```

Notice the use of `redirect_uri`. 
My question is - Is your identity provider not ignoring `redirect_uri`.

**Comment by tikurahul** [comment]
FWIW Google requires that the client specify a `redirect_uri` when making a request to the `token` endpoint.

**Comment by aberasarte** [comment]
Thanks @tikurahul for your fast reply!

> Looking into this further. Looks like redirect_uri is not an expected property. However, the documentation listed at https://tools.ietf.org/html/rfc6749#section-4.1.3 actually uses the following example:

That section explains how to ask for an access token using the authorization code returned by the authorization server. Notice the `grant_type=authorization_code` in the example you posted. I'm talking about the `refresh_token` grant_type which is explained in [section 6](https://tools.ietf.org/html/rfc6749#section-6). According to the spec, these are the allowed parameters for the `refresh_token` grant_type:

```
   grant_type
         REQUIRED.  Value MUST be set to "refresh_token".

   refresh_token
         REQUIRED.  The refresh token issued to the client.

   scope
         OPTIONAL.  The scope of the access request as described by
         Section 3.3.  The requested scope MUST NOT include any scope
         not originally granted by the resource owner, and if omitted is
         treated as equal to the scope originally granted by the
         resource owner.
```

> My question is - Is your identity provider not ignoring redirect_uri.

Yes, it is ignoring it and I guess that most identity providers do but I think that is better to follow the specification and stop sending it. At least it shouldn't be required when the `grant_type` is `refresh_token`. 

I've taken a look at the `AppAuth-Android` project and as far as I see, they are not sending the `redirect_uri` when refreshing the token:
https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthState.java#L609

**Comment by tikurahul** [comment]
Given Google requires the use of `redirect_uri` I think the best work-around you have is to subclass the corresponding request type and not send in the `redirect_uri` when exchanging the `code` for the `refresh_token`.

**Comment by FrodeI** [comment]
This is a valid bug report, and should not have been closed. TokenRequest should not have redirectUri as a mandatory field, and it should not be sent on grant_type=refresh_token. There is never a token refresh using code.
