### ISSUE TITLE
Avoid use of `includes()` for IE

### ISSUE THREAD

**Issue by jakefeasel** [openid/AppAuth-JS#117]
## Expected Behavior
When using a fetch polyfill with IE, the current "FetchRequestor" implementation should be suitable.

## Describe the problem
The FetchRequestor implementation uses the [includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) method. As you can see from the [browser compatibility table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes#Browser_compatibility), Internet Explorer does not support this function. Therefore, an additional polyfill would have to be added just to handle this one use of `includes`.

#### [REQUIRED] Actual Behavior
AppAuth-JS with a fetch polyfill in IE 11 fails (in particular, when making a request that isn't specifically a json data type).

#### [REQUIRED] Steps to reproduce the behavior
Use AppAuth-JS in Internet Explorer 11, with a fetch polyfill (whatwg-fetch, for example). Then make a token revocation request - this type doesn't expect JSON, and so the problematic `includes` code checking the content type will be triggered (and will fail).

#### [REQUIRED] Environment

  * AppAuth-JS version: 1.2.0
  * AppAuth-JS Environment: Internet Explorer 11

**Comment by tikurahul** [comment]
Thanks for the PR. The changes look good.

**Comment by tikurahul** [comment]
Can you please sign the CLA ?

**Comment by jakefeasel** [comment]
Sorry for the delay; my first attempt at filling out the forms was incorrect. All resolved now.
