### ISSUE TITLE
npm install broken

### ISSUE THREAD

**Issue by simihartstein** [openid/AppAuth-JS#13]
I'm on a Windows 10 machine with node 8.1.4 and npm 5.0.3.

After cloning the repository, opening it in Visual Studio Code, and using the bash shell to "npm install", I get the following output with errors:

$ npm install

> fsevents@1.1.2 install D:\BR\AppAuth-JS\node_modules\fsevents
> node install

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> @openid/appauth@0.1.7 prepublish D:\BR\AppAuth-JS
> npm run-script build-app

> @openid/appauth@0.1.7 prebuild-app D:\BR\AppAuth-JS
> npm run-script compile

> @openid/appauth@0.1.7 precompile D:\BR\AppAuth-JS
> npm run-script clean && npm run-script format

> @openid/appauth@0.1.7 clean D:\BR\AppAuth-JS
> rm -rf built

> @openid/appauth@0.1.7 format D:\BR\AppAuth-JS
> clang-format -i -style=file src/**.ts

invalid argument
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @openid/appauth@0.1.7 format: `clang-format -i -style=file src/**.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @openid/appauth@0.1.7 format script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SH\AppData\Roaming\npm-cache\_logs\2017-07-14T19_21_02_021Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @openid/appauth@0.1.7 precompile: `npm run-script clean && npm run-script format`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @openid/appauth@0.1.7 precompile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SH\AppData\Roaming\npm-cache\_logs\2017-07-14T19_21_02_048Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @openid/appauth@0.1.7 prebuild-app: `npm run-script compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @openid/appauth@0.1.7 prebuild-app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SH\AppData\Roaming\npm-cache\_logs\2017-07-14T19_21_02_071Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @openid/appauth@0.1.7 prepublish: `npm run-script build-app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @openid/appauth@0.1.7 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by tikurahul** [comment]
Can you actually submit the debug logs at `C:\Users\SH\AppData\Roaming\npm-cache_logs\2017-07-14T19_21_02_048Z-debug.log` ? There might be something throwing off clang format.

**Comment by simihartstein** [comment]
Hi tikurahul. I appreciate the assistance.
[2017-07-14T19_21_02_021Z-debug.txt](https://github.com/openid/AppAuth-JS/files/1155853/2017-07-14T19_21_02_021Z-debug.txt)
[2017-07-14T19_21_02_048Z-debug.txt](https://github.com/openid/AppAuth-JS/files/1155855/2017-07-14T19_21_02_048Z-debug.txt)
[2017-07-14T19_21_02_071Z-debug.txt](https://github.com/openid/AppAuth-JS/files/1155854/2017-07-14T19_21_02_071Z-debug.txt)

**Comment by tikurahul** [comment]
Hi @simihartstein. Thanks for the logs. Can you please check to see if `clang-format` is correctly on your `PATH`. Can you just execute `clang-format` stand alone, like so:

```bash
clang-format -i -style=file src/**.ts
```

If that fails, could you please copy the full stdout|err and paste it in here?
Sorry for the back and forth. I don't have a Windows Machine to test with.

**Comment by simihartstein** [comment]
I didn't have clang-format installed globally, so it wasn't in my PATH. However, this shouldn't be necessary as npm should handle that.

Anyway, for troubleshooting, I installed clang-format globally and added it to my PATH. When I run that clang-format command directly in the Git bash shell, it gives no output or errors, and a return value of 0.

I would guess the problem is that, even when running npm through the Git Bash, these commands are interpreted as if they were running through the standard Windows shell; so globbing isn't supported. The same clang-format command executed through the Windows shell gives the 'invalid argument' error.

A solution to this would be to use the 'clang-format --glob' parameter. Would you check to see if the following command works on Linux?
`clang-format -i -style=file --glob=src/**.ts`

**Comment by tikurahul** [comment]
That's correct. I may have had `clang-format` installed globally, so i missed that step.
I will check for the `--glob` parameter, as well.

I will have a fix for this soon. Thanks for helping me debug this.
