### ISSUE TITLE
Multiple scopes

### ISSUE THREAD

**Issue by techterbium** [openid/AppAuth-JS#130]
* AppAuth-JS version: latest
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): Node (Electron)

Is there a way to request more than one scope using `AuthorizationRequest`?

**Comment by tikurahul** [comment]
Yes. Scopes are space delimited and case-sensitive.
You should pass them in as `scope1 scope2 ..`

https://tools.ietf.org/html/rfc6749#section-3.3
