### ISSUE TITLE
completeAuthorizationRequestIfPossible: error handling

### ISSUE THREAD

**Issue by jnoga** [openid/AppAuth-JS#134]
Hi,

I've been facing an issue in a project  related with the `completeAuthorizationRequestIfPossible` function in `authorization_request_handler.ts`.

The problem is that if I refresh my website during the complete authorization process it may end up in an incosistent state. The reason is that the function [completeAuthorizationRequest](https://github.com/openid/AppAuth-JS/blob/master/src/redirect_based_handler.ts) returns a null value because it cannot find the related authorization request local storage value. 
In this situation, the authorization flows stops in [completeAuthorizationRequestIfPossible](https://github.com/openid/AppAuth-JS/blob/master/src/authorization_request_handler.ts#L128) with the log `No result is available yet`. 

So my request is: **Would you consider calling `notifier.onAuthorizationComplete` also in error cases?** The function is prepared for that and in this way the error handling would be delegated in the user code through the  [setAuthorizationListener](https://github.com/openid/AppAuth-JS/blob/master/src/authorization_request_handler.ts#L139) function instead of dying in the libray code.

Thanks in advance

**Comment by pixtron** [comment]
Can't 100% follow how to reproduce the error your facing. Could you provide steps to reproduce the error?

**Comment by jnoga** [comment]
I follow these steps:

1. I start with an clean flow calling [performAuthorizationRequest](https://github.com/openid/AppAuth-JS/blob/master/src/authorization_request_handler.ts#L147) to obtain the required `code`.
2. The flow redirects to the applicaction again (with the `code` param in the URL), I put a breakpoint before the [completeAuthorizationRequest](https://github.com/openid/AppAuth-JS/blob/master/src/redirect_based_handler.ts#L130) finishes.
3. I refresh my app, with the `code`param in the URL.
4. The app detects the `code` in the URL so it tries to complete the authorization request, [this.storageBackend.getItem(AUTHORIZATION_REQUEST_HANDLE_KEY)](https://github.com/openid/AppAuth-JS/blob/master/src/redirect_based_handler.ts#L87) returns null and the flow fails/stops in [completeAuthorizationRequestIfPossible](https://github.com/openid/AppAuth-JS/blob/master/src/authorization_request_handler.ts#L127)

Let me know if you can reproduce it

**Comment by aberasarte** [comment]
It would be great to know why this has been closed. The issue still persists and IMHO it makes sense to call `notifier.onAuthorizationComplete` when there is an error.
