### ISSUE TITLE
Token response doesn't match response returned from service

### ISSUE THREAD

**Issue by jestrickler** [openid/AppAuth-JS#138]
#### [REQUIRED] Describe expected behavior
Response from performTokenRequest would match response created by service

#### [REQUIRED] Actual Behavior
I'm not sure if it's behaving as designed, I need to do some configuration, or there's a problem... But the response generated from the service and in the chrome dev tools window is:
```
const realResponse = {
  "access_token": "eyJhbGciOiJS...",
  "token_type": "bearer",
  "refresh_token": "eyJhbGciOiJS...",
  "expires_in": 35999,
  "scope": "read",
  "Department": "My Department",
  "Organization": "My Organization",
  "Unit": "My Unit",
  "jti": "23a63b1c...",
  "username": "John.Doe@fake.com",
  "authorities": [
    "ROLE_ADMIN",
    "ROLE_USER",
  ]
}
```
However, when I get the response in code, many of the fields are missing:
```
const response = {
  "accessToken": "eyJhbGciOiJS...",
  "tokenType": "bearer",
  "expiresIn": 35999,
  "refreshToken": "eyJhbGciOiJS...",
  "scope": "read",
  "issuedAt": 1576705491
}
```

#### [REQUIRED] Steps to reproduce the behavior
Here's the applicable code:
```
const configuration = new AuthorizationServiceConfiguration({
  authorization_endpoint: process.env.REACT_APP_AUTH_URI,
  token_endpoint: process.env.REACT_APP_TOKEN_URI
});
const tokenHandler = new BaseTokenRequestHandler(new FetchRequestor());

export const fetchToken = (code) => {
  const tokenRequest = new TokenRequest({
    client_id: process.env.REACT_APP_CLIENT_ID,
    redirect_uri: process.env.REACT_APP_REDIRECT_URI,
    grant_type: GRANT_TYPE_AUTHORIZATION_CODE,
    code: code,
    refresh_token: undefined,
    extras: {}
  });
  return tokenHandler.performTokenRequest(configuration, tokenRequest);
};

fetchToken(code).then(response => {
  console.log('TOKEN:', JSON.stringify(response));
  ...
}
```

#### [REQUIRED] Environment

  * AppAuth-JS version: "@openid/appauth": "^1.2.6"
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): "react": "^16.12.0"
  * Source code snippts (inline or JSBin)

**Comment by tikurahul** [comment]
I think you might be using a different `scope`, which is why the token has different info.

**Comment by jestrickler** [comment]
Thank you. Can you please explain? I am calling in-house OAuth provider services. The backend returns the expected response as I can see in the network tab of Chrome 'inspect', but the AppAuth.js library returns a subset of that data. Is that because of the 'scope'? The scope I am using is 'read'. What setting should I use to get the full response?

**Comment by tikurahul** [comment]
The other token also looks like an `idToken` to me. Do your endpoints issue and `idToken` as well ?

So the one thing you should do is to sign in the service from an incognito window while looking at all the network requests being made. My guess is at some point the `idToken` which is a `JWT` is what they are holding on to. 

The token format aside, do you need the user information ? You might want to make a request to the `userInfo` endpoint using the access token you have to get that info as well.

**Comment by jestrickler** [comment]
As I mentioned, everything is in-house development, React client, backend services, OAuth provider. The client calls the OAuth login, and gets the code. Then it calls a backend service wrapper around the token exchange. The backend adds the client_secret and calls the OAuth token exchange, then adds some extra app specific user info to the response before returning to the client. The 'access_token' from OAuth is JWT. There is no idToken. I looked in incognito, but see the same as I described above. 

We are considering adding a userInfo endpoint to provide the data, but I'm still not clear as to why the extra data is filtered out by the library. Does AppAuth expect the token response to be a particular format and disregard additional data? Does additional data need to follow a particular format? 

Thanks again, I appreciate your responses!

**Comment by tikurahul** [comment]
Yes, we only care about what is defined in the spec. 

Here is the actual link to the source code. 

https://github.com/openid/AppAuth-JS/blob/master/src/token_response.ts

The best thing for you to do is to extend `BaseTokenRequestHandler` and override the behavior defined here. 

https://github.com/openid/AppAuth-JS/blob/master/src/token_request_handler.ts
