### ISSUE TITLE
Implementing also support for OAuth 2.0 for Browser-Based Apps

### ISSUE THREAD

**Issue by mitar** [openid/AppAuth-JS#139]
So there is [OAuth 2.0 for Browser-Based Apps draft](https://tools.ietf.org/html/draft-ietf-oauth-browser-based-apps-04). It seems similar to the RFC 8252 - OAuth 2.0 for Native Apps, so maybe this library could support both?

**Comment by jakefeasel** [comment]
There is already support for them, though using AppAuth directly might be difficult. Consider using https://github.com/Forgerock/appAuthHelper to make this easier to use.

**Comment by tikurahul** [comment]
AppAuth supports both. If you want to look at example apps, they are a part of the repo.
