### ISSUE TITLE
AppAuth + NativeScript = ReferenceError: $ is not defined on JQueryRequestor.xhr

### ISSUE THREAD

**Issue by gabrielg-dev** [openid/AppAuth-JS#140]
Hi, I apologize for re-asking an old one, but it has been pass 2 years ...

I'm trying to use AppAuth (1.2.6) in a NativeScript project, but when calling to AuthorizationServiceConfiguration.fetchFromIssuer, I get this error:

JS: ReferenceError: $ is not defined
JS:     at JQueryRequestor.push.../node_modules/@openid/appauth/built/xhr.js.JQueryRequestor.xhr (file:///node_modules/@openid/appauth/built/xhr.js:50:0)

Could you give me some advice/comment regarding to this?

Thanks in advance.

**Comment by ArthurKnoep** [comment]
Hi, I have the exact same problem with a react application

**Comment by tikurahul** [comment]
You need to provide your own requester or add `jquery` to your project.
