### ISSUE TITLE
Remove "@types/jquery" from dependencies

### ISSUE THREAD

**Issue by Karfroth** [openid/AppAuth-JS#142]
## Expected Behavior
Do not use "@types/jquery" in dependency.

## Describe the problem
In the project, we are trying to use AppAuth-js in a shared library for multiplatform even though it is not actually supported based on README. We believe that we could try by writing some classes same as Node.JS, but a dependency for "@types/jquery" blocks it and actually this project does not have a strict dependency to JQuery except `JQueryRequestor`.

I think `AppAuth-JS` can write it's own type definition to replace `JQueryAjaxSettings` and remove `JQueryRequestor`.

Technically this looks possible. I could compile both web and RN project when I removed `JQueryRequestor` and `JQueryAjaxSettings` in my forked project.

  * AppAuth-JS version: 1.2.7
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): RN

**Comment by tikurahul** [comment]
Why do the typings matter though ? They are just types. Is this because you are not being able to build interfaces around them for multi-platform ?

**Comment by Karfroth** [comment]
Yes, they are just types. but `@types/jquery` requires typescript library `DOM` and it makes conflict with `@types/react-native`.

**Comment by oriSomething** [comment]
Also it can create issues with TS complier that doesn't handle well multiple versions of the same library
