### ISSUE TITLE
NodeBasedHandler errors during build electron

### ISSUE THREAD

**Issue by JohnyHHH** [openid/AppAuth-JS#143]
Hi,

I have encountered below issue while run build electron project.
This happen when  this.authorizationHandler = new NodeBasedHandler().
Need help. I have npm install latest openid/appauth, and problem still persist.

If change to this.authorizationHandler = new RedirectRequestHandler();
No error seen.

![image](https://user-images.githubusercontent.com/58418444/77299196-11529b80-6d27-11ea-873d-c52c23782f6a.png)

**Comment by tikurahul** [comment]
You are missing typings to for `node`.

**Comment by JohnyHHH** [comment]
hi, my node version is 12.16.1 (this is latest for now)
I tried on the sample [link](https://github.com/googlesamples/appauth-js-electron-sample), it was able to run without error.

This happen when i try to test run the sample flow in my project. I did not sure is there any setup/environment that my project is lack of.

**Comment by JohnyHHH** [comment]
My project is Electron + Angular. Will this be something related to [this](https://github.com/kubernetes-client/javascript/issues/218)?

**Comment by tikurahul** [comment]
Yeah. I think that might be it.

**Comment by JohnyHHH** [comment]
Anyone can advice what should i do or settings to implement this into electron angular project?

**Comment by JohnyHHH** [comment]
Just to update regarding this issue. Since the modules is for node (not for Angular), hence i have move my codes to written in electron instead of Angular. This solve my problem now. thanks.

**Comment by sonoftherock** [comment]
Having the same issue with electron + react project. Do you mean that you simply stopped using Angular for your components to solve the problem?

**Comment by JohnyHHH** [comment]
Just don't use the modules in Angular. You can implement the modules in electron.

**Comment by tikurahul** [comment]
Given its not an `AppAuth-JS` issue I am closing the issue.
