### ISSUE TITLE
Entries in browser localStorage

### ISSUE THREAD

**Issue by jestrickler** [openid/AppAuth-JS#144]
I took a look at my browser localStorage and found a lot of values that seem to be generated from the AppAuth-JS library. 30+ for the Dev server app, and 100+ for my localhost where I develop. The entries seem to have a random key which when coupled with the quantity makes me suspect they are never purged and would eventually use up the space and lead to errors. Does the library manage this storage? Am I missing anything on my end?

I'm using: "@openid/appauth": "^1.2.6"

<img width="510" alt="Screen Shot 2020-05-21 at 2 09 27 PM" src="https://user-images.githubusercontent.com/3867506/82591044-b42f6680-9b6c-11ea-8b7c-a8eef789a8eb.png">

**Comment by baruchvlz** [comment]
I'm using `^1.2.8` and these local storage entries do not exist at any moment during the authflow.

**Comment by KevinDanikowski** [comment]
I've found that although it creates these entries in storage, it doesn't actually do anything with them. There isn't much documentation on how to manage it either.

**Comment by tikurahul** [comment]
They should be cleared once the authorization requests are complete. If you have abandoned OAuth flows, you will see this, and you can clear `localStorage` at that point.
