### ISSUE TITLE
Make 'useHash' in RedirectRequestHandler (completeAuthorizationRequest) configurable

### ISSUE THREAD

**Issue by rostigerloeffel** [openid/AppAuth-JS#147]
## Expected Behavior
It should be configurable whether RedirectRequestHandler uses the query hash oder search string to retrieve state, code and error. 

#### [REQUIRED] Actual Behavior
Currently, RedirectRequestHandler always tries to parse the query hash to retrieve the aforementioned parameters: https://github.com/openid/AppAuth-JS/blob/master/src/redirect_based_handler.ts#L100

#### [REQUIRED] Environment
  * AppAuth-JS version: 1.2.7
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): Chrome 83.0.4103.116

**Comment by tikurahul** [comment]
It’s already configurable because you can use your own query string handler.

**Comment by tikurahul** [comment]
Here is a related pull request and discussion.  

https://github.com/openid/AppAuth-JS/pull/146
