### ISSUE TITLE
 Using `search` when parsing the url in `completeAuthorizationRequest`

### ISSUE THREAD

**Issue by jinf-0805** [openid/AppAuth-JS#148]
## Expected Behavior

Be able to parse the query string with `search`

## Describe the problem

This is a follow up question on a closed Pull Request #146 

My situation is that I get a redirect with the url like this:
`https://something.darkside.com/code=440883ea9600d9&state=wRX7HLyXCp#/main`

The application is written is AngularJs and we are not doing anything special when receiving the redirect from the provider. As per the discussion in the PR, it was mentioned that there is no support for query based redirects because of a security vulnerability. The author of the PR said he got around it by changing the response type to `code token` which our provider does not support.

It would be greatly appreciated if you could share what options are available in order for the application to use the default `hash` in parsing the url. At the moment, we are forced to use `search` and had make a change in `redirect_base_handler` by changing the parameter in `utils.parse` from `true` to `false`.

Sorry, trying to label this as a question but it won't allow me to do so.

#### Steps to reproduce the behavior
On redirect from the provider, processing `completeAuthorizationRequest`

#### Environment

   * AppAuth-JS version: 1.2.7________________
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): Browser_______________________
  * Source code snippts (inline or JSBin)

**Comment by tikurahul** [comment]
Here is the discussion around how to do that:

https://github.com/openid/AppAuth-JS/pull/146

`AuthorizationRequestHandler` can be constructed with a subclass of `QueryStringUtils` that looks like this:

```
class NoHashQueryStringUtils extends BasicQueryStringUtils {
  parse(input: LocationLike, useHash?: boolean): StringMap {
    return super.parse(input, false /* never use hash */);
  }
}
```
