### ISSUE TITLE
Parameter handling with Authorization Code Grant with PKCE

### ISSUE THREAD

**Issue by blaugold** [openid/AppAuth-JS#151]
I ran into a problem when using Authorization Code Grant with PKCE where the authorization response is not recognized. As far as I understand the spec for [Authorization Code Grant](https://tools.ietf.org/html/rfc6749#section-4.1.2) the response parameters should be included as query parameters, and that is what Auth0 does in my case. [`RedirectRequestHandler`](https://github.com/openid/AppAuth-JS/blob/12ad9aaf9f98622facb73b2f8883bc9bf58902bb/src/redirect_based_handler.ts#L100) only looks at the fragment of the URL, which would be right for the Implicit Grant.

Am I misunderstanding something? I'm no expert in OAuth.

**Comment by danlamanna** [comment]
https://github.com/openid/AppAuth-JS/issues/137 might help. 

see also: https://github.com/openid/AppAuth-JS/pull/57#issuecomment-387223806.

**Comment by blaugold** [comment]
Thanks @danlamanna. Going to use the solution from those issues.
