### ISSUE TITLE
Type for `expiresIn` is incorrect.

### ISSUE THREAD

**Issue by baruchvlz** [openid/AppAuth-JS#152]
According to the TokenResponse [type](https://github.com/openid/AppAuth-JS/blob/master/src/token_response.ts#L68) definition, `expiresIn` is marked as `number` but in reality is a `string`.

![Screenshot 2020-08-25 at 15 31 19](https://user-images.githubusercontent.com/14321495/91181254-00002780-e6e9-11ea-868c-33c114065dfe.png)

*Edit*

I changed `NodeRequestor` for `FetchRequestor` to see the response:

![Screenshot 2020-08-25 at 15 40 34](https://user-images.githubusercontent.com/14321495/91181866-bc59ed80-e6e9-11ea-9908-0bea4a70280d.png)

Could this type error be an issue with the provider?

#### [REQUIRED] Environment

  * AppAuth-JS version: ^1.2.8
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): Node

**Comment by tikurahul** [comment]
You are right. It should actually be a `string`. Interestingly the only reason why this actually works is because JavaScript coerces the `string` to a `number` type when `<`, `>` or their variants are used. :scream: 

I can fix this.

**Comment by baruchvlz** [comment]
> Interestingly the only reason why this actually works is because JavaScript coerces the string to a number type when <, > or their variants are used

Yea.. the gold ole `"1" + 1 = "11"`. Thanks for looking into this.
