### ISSUE TITLE
How do I check if a oAuth service is compatible with AppAuth-JS?

### ISSUE THREAD

**Issue by amanguptadev** [openid/AppAuth-JS#159]
I'm trying to connect Intercom.com oAuth using AppAuth-JS but getting a 404 error.

The config I'm using:
```
           "openIdConnectUrl":"https://app.intercom.com",
            "clientId": "secret_client_id",
            "redirectUri":"http://127.0.0.1:8000",
            "scope":""
```

Intercom oauth documentation:
https://developers.intercom.com/building-apps/docs/setting-up-oauth

**Comment by tikurahul** [comment]
I would check the OAuth well known endpoints. 

Usually the tricky part is the client registration when every IDP has their own conventions. If you can get things to work with this configuration, then its okay maybe? :smile:

**Comment by amanguptadev** [comment]
Hey @tikurahul, thank you for the quick response. It's not working with the current configuration for Intercom (:

Can I manually set up the authorization URLs?

I'm building an electron app that lets you authenticate multiple cloud apps, I'm successfully able to authenticate Google cloud apps like Drive, Analytics, and Calendar. I thought it would work for all the could apps that has oAauth, maybe I'm wrong 😅

**Comment by tikurahul** [comment]
Yes, you can just manually specify the authorization and the token endpoint and craft the AuthorizationRequest manually.

**Comment by amanguptadev** [comment]
Do I need to make these changes to the files in the node_modules folder or it's possible by passing variables to flow.ts?

**Comment by tikurahul** [comment]
Just passing them into the constructor for `AuthorizationRequest`. 

Here is an example: https://github.com/openid/AppAuth-JS/blob/master/src/node_app/index.ts#L79
