### ISSUE TITLE
What's the best way to redirect on the original URL?

### ISSUE THREAD

**Issue by sneko** [openid/AppAuth-JS#162]
Hi,

Thanks for your library, very useful!

Just got a question about redirecting the user to the initial URL where he started the login flow. From what I understand the callback URL should not by dynamic, but at least I could use the state to store inside the initial "view/page" the user was on.

What do you think? Is there any other solution?

Thank you,

**Comment by tikurahul** [comment]
You can add URL fragments to the callback URL. So something like `https://server/callback#destination`.

**Comment by sneko** [comment]
Hi @tikurahul ,

Thanks for your quick answer!

Just wondering: so why it's the usage of "state" if the "fragment/hash" can be use to pass information?

And if I want to pass multiple information, does it make sense to encode a JSON object and pass it as hash/fragment, or maybe in this case the state is more appropriate?

**Comment by tikurahul** [comment]
`state` is not meant to be used for this. It's a part of the OAuth2 protocol where the RP exchanges a combination of `code` + `state` (not accounting for PKCE) for a `refreshToken` + `accessToken`.

`state` is also meant to be random because and is one of the ways the Authorization server can verify that the app was the one that initiated the request when exchanging the `code` for the `refreshToken`. This is because it's not enough to know the code. You need to know a combination of both `code` and `state`.

**Comment by sneko** [comment]
Ok I see what you mean :) 

I was thinking about the state since I saw multiple "articles" talking about this way (eg. https://auth0.com/docs/protocols/state-parameters#use-the-stored-url-to-redirect-users).

From what I understand in your message, if I set up an objet like:
```
{
  random: 'a2erfdf',
  redirectUrl: '/articles/6',
}
```

Then I encode it to then inject into the state, it would keep the standard valid since the random key was non-guessable? Before setting the state, I store the stringified object, and when receiving the response I compare with what's locally?

PS: still wondering for having multiple properties, if encoding a JSON and passing as fragment is something "valid"?

Thanks again,

**Comment by tikurahul** [comment]
Sorry. I mis-spoke. Should have some coffee to wake me up first. 

`state` is something you care about to make sure the authorization response was for a request _you_ made. So it should be still random-ish. 

You could encode more information but there are limits to what a query string can carry. So be aware of that. 

Token requests are protected by PKCE.

**Comment by sneko** [comment]
So, I tried the "first" option with fragment... but the issue is that my OIDC "server" requires the full URL (including what's after the hash) to be registered as an allowed redirect_uris... so it doesn't work since I won't register all possible paths of my app ^^...

And the AppAuth.js wrapper I use (for Ionic) doesn't allow modifying the state to use the "second" option. I need to see if I can access this since that's JS, otherwise will take more time to make a PR.

"Third" option would be to bypass AppAuth and just store in it the local storage... but that's durty :(

**Comment by tikurahul** [comment]
* Regarding option1, that is very :disappointed: 
* Option 2, you don't need to modify `state` you can pass it into the `AuthorizationRequest` when you construct it. 
Maybe give that a shot ?

**Comment by sneko** [comment]
Yeah but I need to make a PR to the wrapper lib I use for Ionic:
https://github.com/wi3land/ionic-appauth/blob/6c097aab214b7b89d17db4d4f03a02d128a2e10a/src/auth-service.ts#L144-L150

They don't allow "modifying/specifying" the state so I need to look at what can be done on this side :)

**Comment by tikurahul** [comment]
Its a`protected` method. Maybe you can just extend it :smile:

**Comment by sneko** [comment]
I did minor changes and pushed a PR on their repo.

Thank you for answering @tikurahul :)

**Comment by tikurahul** [comment]
No problem ! Happy to help.
