### ISSUE TITLE
Google Api Registration

### ISSUE THREAD

**Issue by nayefmhmd85** [openid/AppAuth-JS#166]
#### [REQUIRED] Environment

  * AppAuth-JS version: ________________
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): _______________________
  * Source code snippts (inline or JSBin)

**Comment by nayefmhmd85** [comment]
I created google Api with clientId,
How Use it in this app

**Comment by tikurahul** [comment]
There is extensive documentation on how to do this. This issue tracker is only for the library and not for general OAuth2 configuration problems.
