### ISSUE TITLE
Adding PATCH HTTP Method Support

### ISSUE THREAD

**Issue by td-edge** [openid/AppAuth-JS#169]
## Expected Behavior

Using the requestor xhr, I would expect there to be support for the PATCH HTTP methods, however, PATCH does not seem to work.

#### Describe expected behavior

Allow PATCH to function as an HTTP method option.

## Describe the problem

Setting up an HTTP interceptor, I created the following method in an angular application:
```
public async request<T>(method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE', url: string, body?: any) {
    const token: TokenResponse = await this.auth.getValidToken();
    return this.requestor.xhr<T>({
      url,
      method,
      data: JSON.stringify(body),
      headers: this.addHeaders(token)
    });
}
```
PATCH is not a supported method as far as I can tell and fails leaving the application. Converting the same call to a POST seems to work. 

#### Actual Behavior

PATCH seems to fail as a request type.

#### Steps to reproduce the behavior

Set up a simple angular application using the code block above as your main HTTP method. Try to complete a PATCH request.

#### Environment

  * AppAuth-JS version: ^1.2.6
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): Angular/Ionic iOS build
  * Source code snippts (inline or JSBin)

**Comment by tikurahul** [comment]
You can swap `requestor` altogether and use something that angular provides. That way you can use a better HTTP client.
