### ISSUE TITLE
Can we add the revocation_endpoint to AuthorizationServiceConfiguration?

### ISSUE THREAD

**Issue by raffis** [openid/AppAuth-JS#17]

**Comment by tikurahul** [comment]
Sure.. do you want to send me a pull request ?

**Comment by raffis** [comment]
yes, coming next week.

**Comment by raffis** [comment]
@tikurahul see pull

**Comment by tikurahul** [comment]
@raffis, Any updates since my comments. I would love to make this a part of AppAuth-JS.

**Comment by raffis** [comment]
@tikurahul I will have some time tomorrow or next week to push an update

**Comment by tikurahul** [comment]
This is fixed !
