### ISSUE TITLE
Need public function to set additional options to pass http request in node_requestor

### ISSUE THREAD

**Issue by SomnathMore** [openid/AppAuth-JS#173]
## Describe the problem
No way though which I can pass addition options i.e. agent/proxy. I have added a public method for it. But dont have access to craate a PR.
#### [REQUIRED] NA

  * AppAuth-JS version: ____1.3.0____________
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): ______Node_________________
  * Source code snippts (inline or JSBin)

**Comment by tikurahul** [comment]
You can just implement your own `Requestor` type and swap it.
