### ISSUE TITLE
depends on '@openid/appauth'. CommonJS or AMD dependencies can cause optimization bailouts

### ISSUE THREAD

**Issue by celvin** [openid/AppAuth-JS#181]
#### [REQUIRED] Describe expected behavior
When compiling in Angular 10, I'm getting the warning: '@openid/appauth'. CommonJS or AMD dependencies can cause optimization bailouts

## Describe the problem
When compiling

#### [REQUIRED] Actual Behavior
Warning: /usr/src/app/src/app/app.module.ts depends on '@openid/appauth'. CommonJS or AMD dependencies can cause optimization bailouts.
ck-servicemesh-webapp                       | For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

#### [REQUIRED] Steps to reproduce the behavior
npm install

#### [REQUIRED] Environment

  * AppAuth-JS version: ^1.3.1
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): node
  * Source code snippts (inline or JSBin)

**Comment by tikurahul** [comment]
The `@openid/appauth` import is an umbrella import for convenience. You can always just import the individual modules.
