### ISSUE TITLE
IFrame Support

### ISSUE THREAD

**Issue by AbhiAgarwal192** [openid/AppAuth-JS#185]
## Describe the problem

If you have two apps and user 1 logged in on app 1 and on another tab in the same browser instance user 1 again opens app1 and logs out. In this case, he/she should be logged out from both the tabs.

#### [REQUIRED] Environment

OpenID configuration has an attribute check_session_iframe. The module is currently not making use of this property.

**Comment by tikurahul** [comment]
The goal of the library was to never implement every feature of the spec. This is something we did not want to support as the library wants to be a bit agnostic to the Javascript runtime you are using. You can however, add this extension on your own.
