### ISSUE TITLE
Request ended with an error  400

### ISSUE THREAD

**Issue by SlowLow32** [openid/AppAuth-JS#193]
#### [REQUIRED] Describe expected behavior

Return TokenREquest Response

## Describe the problem

Basically, I'm trying to get AppAuth-JS to work with WHMCS OpenID, but having little success. 
It seems to work with google but when I switch it to WHMCS config, it fails after it makes a TokenRequest and then it's waiting for the TokenResponse, instead it returns "Request ended with an error  400". I have tested the WHMCS OpenID configuration with Postman, and it worked but does not work when using the Github link below.

Do I need a refreshToken to complete the process?
Looks like I need it, but WHMCS doesn't return it, any way to bypass this?

The left side of the image uses google and the right side uses WHMCS

![image](https://user-images.githubusercontent.com/87282255/128568952-3a7f0e45-46e6-4988-aa1c-6400b07e3db3.png)

#### [REQUIRED] Environment

  * AppAuth-JS version: 1.3.1
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): NodeJs
  * Source code snippts (inline or JSBin)

Using the below git for testing.
https://github.com/googlesamples/appauth-js-electron-sample

**Comment by tikurahul** [comment]
This is an IDP issue, and not specifically an issue with AppAuth.
