### ISSUE TITLE
Javascript Implemantation:Code still visible in the address bar after redirection

### ISSUE THREAD

**Issue by samanthaburboz** [openid/AppAuth-JS#202]
## Expected Behavior

After the user authorized he should be redirected to the home page and the code should not be visible in the address bar 

localhost:9000/

## Describe the problem
We are trying to implement AppAuthJs in a plain Javascript and facing the following issue

#### [REQUIRED] Actual Behavior

localhost:9000/callback?code=bKyHjsQ-yJXwW8cOrya4Zr3eAQGKnugfdOlXjdlzRJ4&state=G7ZBLaGxYD

**Also can you please provide a example for plain Javascript implementation.**
#### [REQUIRED] Environment

  * AppAuth-JS version: _____________"@openid/appauth": "^1.3.1"___
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): _______________________
  * Source code snippts (inline or JSBin)

**Comment by tikurahul** [comment]
This is something you can control  on your end. This is got nothing to do with the library itself.
