### ISSUE TITLE
RedirectRequestHandler.completeAuthorizationRequest() assumes that queryParams are returned in the hashed portion of the URL

### ISSUE THREAD

**Issue by sandyboon** [openid/AppAuth-JS#203]
#### While constructing the AuthorizationRequest object, set the response_mode value to 'query'.
const request = new AuthorizationRequest({
            client_id: fcAuthConfig.clientId,
            redirect_uri: `${window.location.origin}${window.location.pathname}`,
            usePkce : true,
            scope:'openid',
            response_type: AuthorizationRequest.RESPONSE_TYPE_CODE,
            extras: {'response_mode': '**query**' }
        });
Perform the authorization request - 
 authorizationHandler.performAuthorizationRequest(authConfig, request);
and then await authorizationHandler.completeAuthorizationRequestIfPossible(); after signing in and redirection.

#### [REQUIRED] Environment

  * AppAuth-JS version: 1.3.1
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...):  Chrome
  * Source code snippts (inline or JSBin)

**Comment by tikurahul** [comment]
You can extend `RedirectRequestHandler` and ignore `useHash`.

**Comment by thardyman** [comment]
e.g. https://github.com/openid/AppAuth-JS/issues/114#issuecomment-1333904882
