### ISSUE TITLE
Angular ionic sample

### ISSUE THREAD

**Issue by layinka** [openid/AppAuth-JS#21]
Hi,
Do you have an example of how i can use this in a mobile android app for Ionic

**Comment by tikurahul** [comment]
What are you trying to accomplish ? On Mobile Android you could use the Google APIs (Google Sign In) which is native, and gives you the functionality you need. If you want to support a non GMS device, you could also consider using [AppAuth-Android](https://github.com/openid/AppAuth-Android).

**Comment by layinka** [comment]
Thanks,
I am trying to implement a login on an ionic 3 mobile app for both android and IOS that will connect to an identity server 4 API backend.
I will like to use a js library directly instead of the google signins which I believe is native to android.

Also ,this should also work in pwa mode as the app will have a base and be built for both android,IOS and web


Sent from my Windows Phone

-----Original Message-----

**Comment by tikurahul** [comment]
Sorry about the delay in replying. For an ionic app, you will have to implement the hooks for launching a custom tab, and handling the redirect either via a Universal URL or an Intent on Android. 
I can offer guidance, and the goal of the library has always been to make this very simple. 

The key is to implement another `AuthorizationRequestHandler` like the one here: 
https://github.com/openid/AppAuth-JS/blob/master/src/node_support/node_request_handler.ts#L30

**Comment by tikurahul** [comment]
@layinka if you have more questions please feel free to re-open this issue.

**Comment by BenjaminKauer** [comment]
@layinka any progress?

**Comment by mraible** [comment]
@BenjaminKauer I wrote an article that shows [how to do Ionic authentication with OAuth](https://developer.okta.com/blog/2017/08/22/build-an-ionic-app-with-user-authentication), maybe you'll find it useful. It doesn't use AppAuth-JS, but it'll get the job done.

I also integrated something similar in the [Ionic Module for JHipster](https://github.com/oktadeveloper/generator-jhipster-ionic), but ended up using [angular-oauth2-oidc](https://github.com/manfredsteyer/angular-oauth2-oidc) so it'd work with Okta and Keycloak. You can read about how it works in [this blog post](https://developer.okta.com/blog/2018/01/30/jhipster-ionic-with-oidc-authentication). Someone recently contributed a way to [make it even better](https://github.com/oktadeveloper/generator-jhipster-ionic/issues/28) by recognizing existing authenticated sessions.

**Comment by BenjaminKauer** [comment]
@mraible Thank you very much. We don't want to use a third-party service as Okta, though. Furthermore we need to implement the Hybrid Flow. It's interesting, that I can't find anyone who has done this before: OIDC Hybrid Flow in Ionic/Angular, using their own IdentityServer.

**Comment by Belicosus** [comment]
@BenjaminKauer I've been at the exact same task the last couple of hours. Currently considering doing the implementation myself with the InApp browser

**Comment by BenjaminKauer** [comment]
@Belicosus that's the way I'll do it.

But I spent a little time with our backend people to discuss whether we could use another flow. We'll probably stick to the Authorization Code Flow and we'll probably use AppAuth-JS instead of [angular-oauth2-oidc](https://github.com/manfredsteyer/angular-oauth2-oidc). Since I can't get [hapi](https://github.com/hapijs/hapi) to work, which is needed for the callback (clientRedirectURI), I'm about to implement a (less sophisticated) server with [express](https://github.com/expressjs/express).

**Comment by mraible** [comment]
angular-auth-aoidc has a silent refresh feature you might be able to use.

**Comment by kioannou** [comment]
@mraible I think you cannot use the silent refresh feature in Ionic (Android or iOS) application app. You cannot setup the silent refresh process for many reasons. It opens a hidden iframe and follows the implicit login process I think. For example you cannot use iframes that required by the silent refresh process (thats why an in-app browser is used). If you have implemented it you can share it. It will be a great help for many developers.

**Comment by mraible** [comment]
@kioannou Good point. I don't have a solution at this time.

**Comment by Belicosus** [comment]
I've started work on a Ionic wrapper for AuthApp. The implementation is very much inspired by @mraible and his article pointing to the use of InAppBrowser to sign in with Facebook.
I expect to finish this tomorrow or wednesday, I'll upload the solution.

**Comment by lostdev** [comment]
@Belicosus if you're going to spend the time doing the work, I would kindly suggest looking into using [a custom URL scheme](https://github.com/EddyVerbruggen/Custom-URL-scheme), rather than using the InAppBrowser. [Google's no longer supports authentication using the InAppBrowser](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html) and it's not longer the recommended approach for several reasons.

Jacques has an an old (but nonetheless relevant) [article ](https://medium.com/@jlchereau/stop-using-inappbrowser-for-your-cordova-phonegap-oauth-flow-a806b61a2dc5)on medium that's a pretty nice read.

**Comment by mraible** [comment]
@Belicosus You might look at [react-native-app-auth](https://github.com/FormidableLabs/react-native-app-auth) for inspiration. That uses the custom URL scheme that @lostdev recommends. I wrote [an article about it for scotch.io](https://scotch.io/tutorials/build-a-react-native-app-and-authenticate-with-oauth-20) recently.

**Comment by BenjaminKauer** [comment]
Thanks for all the ideas. I've got an almost working solution for the Authorization Code Flow with silent refresh. As soon as I'm done I'll probably write an article.

FYI: I needed to implement a custom AuthorizationRequestHandler and a TokenRequestHandler. The latter is using a custom URL scheme and the system browser.

**Comment by tikurahul** [comment]
Once you have an article, could you please link your article and the source code? That will help others who want to do something similar (implement their own `AuthorizationRequestHandler`.  I will also link it from the `README` so others can discover it.

**Comment by BenjaminKauer** [comment]
Of course I will :)

**Comment by maurotn** [comment]
Hi all, are there any news about this issue?
We want to add OAuth2 authentication in an Ionic app (Identity Server 3 as OAuth2 provider).
Currently we have implemented implicit flow authentication with https://github.com/IdentityModel/oidc-client-js but we would enhance our security adding PKCE.

Thanks...

**Comment by Belicosus** [comment]
@maurotn A project deadline has kept me from creating a usable package for this, but we did indeed implement the AppAuth JS library in our Ionic app.
We are utilizing the AppAuth project, but have implemented/overridden the vital parts like requestor, AuthorizationRequestHandler and RequestHandler. 
Our app implements the Open ID Connect Hybrid flow  as implemented in IdentityServer 4.
I would like to put this in a npm package, but I haven't had the time. If you're interested I'll try to find the time tomorrow to put the code in a github repo for you to use as an example.

**Comment by nmocruz** [comment]
@maurotn 

something like this

` class CordovaAuthorizationRequestHandler extends AuthorizationRequestHandler {

  private currentRequest: AuthorizationRequest = null;
  constructor(
    public locationLike: LocationLike = window.location,
    utils = new BasicQueryStringUtils(),
    generateRandom = cryptoGenerateRandom
  ){
    super(utils, generateRandom)
  }
  performAuthorizationRequest(configuration: AuthorizationServiceConfiguration, request: AuthorizationRequest): void {
    let handle = this.generateRandom();
    let url = this.buildRequestUrl(configuration, request);

    this.currentRequest = request;

    log('Making a request to ', request, url);

    SafariViewController.isAvailable(isAvaliable=>{
      if(isAvaliable){
        SafariViewController.show({url});
      }
      else{
        cordova.InAppBrowser.open(url);
      }
    });
  }
  protected completeAuthorizationRequest(): Promise<AuthorizationRequestResponse> {

    return new Promise(resolve => {
      SafariViewController.hide();
      if(!this.currentRequest)
        resolve();
      let currentUri = `${this.locationLike.origin}${this.locationLike.pathname}`;
      let queryParams = this.utils.parse(this.locationLike, true /* use hash */);
      let state: string|undefined = queryParams['state'];
      let code: string|undefined = queryParams['code'];
      let error: string|undefined = queryParams['error'];
      log('Potential authorization request ', currentUri, queryParams, state, code, error);
      let shouldNotify = state ===  this.currentRequest.state;
      let authorizationResponse: AuthorizationResponse|null = null;
      let authorizationError: AuthorizationError|null = null;
      if (shouldNotify) {
        if (error) {
          // get additional optional info.
          let errorUri = queryParams['error_uri'];
          let errorDescription = queryParams['error_description'];
          authorizationError =
              new AuthorizationError(error, errorDescription, errorUri, state);
        } else {
          authorizationResponse = new AuthorizationResponse(code, state!);
        }
        log('Delivering authorization response');
        resolve({ request: this.currentRequest,
                  response: authorizationResponse,
                  error: authorizationError
                } as AuthorizationRequestResponse );
      }else{
        log('Mismatched request (state and request_uri) dont match.');
        return Promise.resolve(null);
      }
    })
  }
}
`

**Comment by maurotn** [comment]
Thanks @Belicosus , yes I'm interested. If you had the time to upload it into a repo it would be great!

**Comment by maurotn** [comment]
Thanks @nmocruz

**Comment by phiamo** [comment]
@Belicosus would be grad if you could put that on github and we could maybe pull it up alltogether!

**Comment by tikurahul** [comment]
@Belicosus @nmocruz Awesome work. 

If you create a GitHub repo, I can link it from this repo so others can discover it.
Thanks for the code snippet which can help folks get started in the meantime.

**Comment by Belicosus** [comment]
Hi guys. @maurotn @twinklekumarp 
Finally got around to put the code on Github. 

[AppAuth-Ionic Github Repo](https://github.com/Belicosus/AppAuth-Ionic)

It still needs some(a lot) polishing if we want to publish it as a npm package, but for now, it should at least get some of you going. Please feel free to post any questions in the issues section.

@tikurahul Do whatever you want with the repo. I don't know if you want to link to it at it's current state. It's up to you 👍

**Comment by tikurahul** [comment]
@Belicosus Thank you for the link. I am going to link it off the `README` so others can discover your approach. Thanks !

**Comment by BenjaminKauer** [comment]
I'm sorry I wasn't able to deliver my solution earlier. We've been busy implementing the EU-GDPR stuff.
Thank you @Belicosus, I'll check your approach, maybe I can contribute something to your repo.

**Comment by Belicosus** [comment]
@BenjaminKauer Fell free to post any questions of suggestions under Issues, or even submit a PR. will be much appreciated :)
