### ISSUE TITLE
Support for http basic authentication 

### ISSUE THREAD

**Issue by raffis** [openid/AppAuth-JS#24]
https://tools.ietf.org/html/rfc6749#section-2.3
> Including the client credentials in the request-body using the two
>    parameters is NOT RECOMMENDED and SHOULD be limited to clients unable
>    to directly utilize the HTTP Basic authentication scheme (or other
>    password-based HTTP authentication schemes).

How the credentials are submitted to the authorization server must be configurable, probably according to the specs from openid (http://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication) whereas basic authentication should be the default if client credentials given.

This is related to both the token endpoint and the revocation endpoint proposed in https://github.com/openid/AppAuth-JS/pull/19.

**Comment by tikurahul** [comment]
We could follow something along the lines of this: https://github.com/openid/AppAuth-android#utilizing-client-secrets-dangerous.

**Comment by tikurahul** [comment]
We don't want to support flows that involve entering credentials for every Auth request.
