### ISSUE TITLE
full implicit flow support?

### ISSUE THREAD

**Issue by raffis** [openid/AppAuth-JS#25]
@tikurahul I know you have mentioned this in https://github.com/openid/AppAuth-JS/issues/8#issuecomment-309239324 but implicit auth would still be cool feature. For SPA implicit auth is required and support for it is basically already there, we only need make sure that the correct data is returned here: https://github.com/openid/AppAuth-JS/blob/master/src/redirect_based_handler.ts#L102  if 'token' (instead code) was requested.

what I do now in my spa as a workaround:
```javascript
const {AuthorizationServiceConfiguration} = require('@openid/appauth/built/authorization_service_configuration.js');
const {AuthorizationRequest} = require('@openid/appauth/built/authorization_request.js');
const {AuthorizationNotifier} = require('@openid/appauth/built/authorization_request_handler.js');
const {RedirectRequestHandler} = require('@openid/appauth/built/redirect_based_handler.js');

var login = {
  init: function() {
    this.notifier = new AuthorizationNotifier();
    this.handler = new RedirectRequestHandler();

    this.notifier.setAuthorizationListener(function (request, response, error) {
      var hash = login.parseAuthorizationResponse();
      if (response && hash.access_token) {
        //do something usefull here with hash.access_token...
      } else {
        //error
      }
       
      //destroy hash
      window.location.hash = '';
    });
    
    this.handler.setAuthorizationNotifier(this.notifier);
    this.handler.completeAuthorizationRequestIfPossible();
  },

  initOidcAuth: function(idp) {  
    AuthorizationServiceConfiguration.fetchFromIssuer(idp.providerUrl).then(configuration => {
      var request = new AuthorizationRequest(
        idp.clientId, idp.redirectUri, idp.scope, 'id_token token', undefined, {'nonce': Math.random().toString(36).slice(2)});
  
      login.handler.performAuthorizationRequest(configuration, request);
    });
  },

  parseAuthorizationResponse: function() {
    var hash = window.location.hash.substr(1);
    var obj = {};
    var pairs = hash.split('&');
    
    for(let i in pairs){
      let split = pairs[i].split('=');
      obj[decodeURIComponent(split[0])] = decodeURIComponent(split[1]);
    }

    return obj;
  }
}
```

**Comment by tikurahul** [comment]
Sorry about the delay in getting back to this. 

I agree. Support is basically almost there. However the problem really is whether the application holds on to the user's password when it needs another access token. 

@WilliamDenniss Any thoughts?

**Comment by panva** [comment]
Isn't the idea behind AppAuth to follow the [BCP](https://tools.ietf.org/html/draft-ietf-oauth-native-apps). On the topic of implicit,

>  8.2.  OAuth Implicit Grant Authorization Flow
>
>  The OAuth 2.0 implicit grant authorization flow as defined in
>  Section 4.2 of OAuth 2.0 [RFC6749] generally works with the practice
>  of performing the authorization request in the browser, and receiving
>  the authorization response via URI-based inter-app communication.
>  However, as the implicit flow cannot be protected by PKCE [RFC7636]
>  (which is a required in Section 8.1), the use of the Implicit Flow
>  with native apps is NOT RECOMMENDED.
>
>  Tokens granted via the implicit flow also cannot be refreshed without
>  user interaction, making the authorization code grant flow - which
>  can issue refresh tokens - the more practical option for native app
>  authorizations that require refreshing.


> However the problem really is whether the application holds on to the user's password when it needs another access token.

I believe this to be the relevant when ROPC is used, which again, is not what AppAuth is bringing.

**Comment by iainmcgin** [comment]
So, my opinion here is that implicit flow is much more common for the web, so supporting this flow is a reasonable request. That said, AppAuth-JS is primarily targeted at native-ish environments like Electron / NWJS / NativeScript right now, and in those environments we definitely don't want people to rely on the implicit flow (as @panva points out from the BCP). AppAuth-JS does of course also work as an OAuth client within the browser too, but we're not ready to fully commit to supporting that usage mode yet.

**Comment by vishal-elear** [comment]
Hi, when can we expect the enhancement with OAuth implicit flow to be added?

**Comment by nmocruz** [comment]
@vishal-elear as I understand from the discussion here, is possible to use just doing the workaround mentioned, but this library is focus on native apps, even ionic/cordova must be considred native in this case, and so it's not the main flow to use this library, maybe you can go with oidc-client-js if you want to use implicit flow, but it will not work if want to stand without prompt the login page every time that token expires.

**Comment by brockallen** [comment]
BTW, oidc-client-js is for browser-based JS clients (IOW implicit flow), and it's OIDC certified: 

https://github.com/IdentityModel/oidc-client-js/
https://www.npmjs.com/package/oidc-client
https://www.npmjs.com/package/oidc-client

**Comment by vishal-elear** [comment]
@nmocruz @brockallen I will have a look at oidc-client-js as it seems more apt for my use-case since I'm looking for something that provides support for implicit flow as the clients in my case are browser-based JS clients (SPAs).

**Comment by nmocruz** [comment]
@vishal-elear if is spa browser go with oidc-client-js because it's specifically designed for client-side browser-based JS apps

**Comment by someone1** [comment]
I actually posted [a question](https://security.stackexchange.com/questions/182873/why-isnt-pkce-encouraged-for-single-page-apps) on StackExchange about this - why is implicit flow still preferred for SPAs? I am using this library for my SPA and only with PKCE, there are many reasons to prefer even a Authorization Code Flow without a client_secret over the implicit flow. 

I appreciate that this package exists and think it would be great if it only supported secure oauth2 flows to encourage developers to use them and make the internet a safer place for all (and alternatives already exist that support those flows as mentioned above)!

**Comment by wi3land** [comment]
if you are using ionic i have created an extension for appauth-js called [ionic-appauth](https://www.npmjs.com/package/ionic-appauth). This includes an implicit flow for use when using a browser with ionic.
