### ISSUE TITLE
Package Managers

### ISSUE THREAD

**Issue by darkcircuituk** [openid/AppAuth-JS#3]
Any plans to release this to the various package managers (npm, etc)? I'm building a mobile (Android/iOS) Cordova app using Angular2, and would love to use this as the oid-client-js library doesn't play nicely with Cordova/Angular2 on a mobile device due to its reliance on a redirect URL, which obviously doesn't play nicely with single page applications. However the thought of manually having to update this package whenever you guys make an update is daunting.

**Comment by tikurahul** [comment]
Please look at the discussion at (https://github.com/openid/AppAuth-JS/issues/2). We're working our way up to supporting more client-side JS frameworks, the library is still pretty new and it will take some time.

Although this library is pretty stable for the intended use cases right now (Chrome Apps, Node CLI and scripting) - I have labelled this library as `0.1.0`. Once we add more support for Cordova / React Native, and stabilize the interfaces - I will publish the library to a package manager and designate the library as a `1.0`.

**Comment by tikurahul** [comment]
I have published AppAuthJS to NPM under `@openid/appauth`.

**Comment by lostdev** [comment]
@tikurahul does this library support Cordova?

Thank you!

**Comment by tikurahul** [comment]
@lostdev - This library can support Cordova, but you are probably better off using something that wraps AppAuth-Android / AppAuth-iOS natively based on the respective platform.
