### ISSUE TITLE
async/await vs event emitter

### ISSUE THREAD

**Issue by stupiduglyfool** [openid/AppAuth-JS#30]
I wasn't sure if I should open another issue for this, but I have been experimenting with replacing the event emitter with promises.. 

[https://github.com/stupiduglyfool/AppAuth-JS/tree/feature/asyncawait](https://github.com/stupiduglyfool/AppAuth-JS/tree/feature/asyncawait)

I have temporarily removed extraneous code from the repo whilst I demo the idea.. 

When I build my application based on this it feels a lot more intuitive and easier to wire up.. async request/reply methods, rather than subscribing to events, then making a request.. 

example usage:

[https://gist.github.com/stupiduglyfool/cfdadb7005ef548f79d91227ee00c89a#file-async-await-consumer-example](https://gist.github.com/stupiduglyfool/cfdadb7005ef548f79d91227ee00c89a#file-async-await-consumer-example)

updated electron async/await handler:
[https://gist.github.com/stupiduglyfool/42197f96f93584b5fdccdca7fc90f785#file-electron_request_handler-ts](https://gist.github.com/stupiduglyfool/42197f96f93584b5fdccdca7fc90f785#file-electron_request_handler-ts)

What do you think?

**Comment by stupiduglyfool** [comment]
Thanks, from what I have seen, the typescript transpiler deals with this sort of problem, you can write async/await in your typescript and it transpiles into promise based code..

**Comment by tikurahul** [comment]
Yeah. I wish everyone just used TypeScript sometimes. 😀
