### ISSUE TITLE
Improve NPM experience

### ISSUE THREAD

**Issue by Meligy** [openid/AppAuth-JS#33]
Hello,
There are a few things that can make NPM usage (and TypeScript experience especially) a lot better.

1. Adding a barrel. An `src/index.ts` file that `export`s all other files in that folder.
2. Adding a `main` property in `package.json` that points to the compiled result of the barrel, ex: `built/index.js`
3. Adding a `types` property in `package.json` that points to the TypeScript declaration of the barrel, ex: `built/index.d.ts`

That'll allow people to `import * as appAuth from '@openid/appauth';`, or have more specific `import`s, as they wish.

Documentation: [TypeScript Docs: Publishing](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)

### P.S.

Thanks heaps for the great work on the library.

### P.P.S.

If you agree with the concept, I can also create a PR for this.

**Comment by tikurahul** [comment]
Yes. I have been meaning to do this as well. Do you want to send me a PR ?

**Comment by tikurahul** [comment]
For information on what types to include in the barrel for web and node environments, please take a look at the `app` and `node_app` folders for reference.

**Comment by Meligy** [comment]
Can I just export everything? This is kinda supported already now.

**Comment by Meligy** [comment]
Also, since we include generated files in repo (OK for now), any particular commands you suggest before pushing? Run all the commands in readme in order?

**Comment by Meligy** [comment]
@tikurahul hey buddy. Have you had a chance to look at the Pull Request? (#34)

Sorry if being a little pushy. There's some great work in here, and would love to see it easily consumable.

Cheers,

**Comment by tikurahul** [comment]
Thanks for the contribution. 👍
