### ISSUE TITLE
Electron sample

### ISSUE THREAD

**Issue by thijscrombeen** [openid/AppAuth-JS#4]
Hi,

Do you have an example on how to use this with Electron?
I'm willing to contribute this sample if you give me some pointers.

I need to know how to set the redirect uri, so that the oauth provider correctly redirects back to electron.

**Comment by tikurahul** [comment]
Electron should just work (given that you can consume code for Node). 
Here is some example code: https://github.com/openid/AppAuth-JS/blob/master/src/node_app/index.ts

**Comment by tikurahul** [comment]
I have published AppAuthJS to NPM as `@openid/appauth`. I will upload my Electron sample if you need help consuming the library.

**Comment by thijscrombeen** [comment]
It would always be nice to have a sample :)

**Comment by iainmcgin** [comment]
A sample is Coming Soon, we'll let you know when it's available.

**Comment by tikurahul** [comment]
The electron sample is now available at https://github.com/googlesamples/appauth-js-electron-sample.
Thank you for being patient.
