### ISSUE TITLE
Register my own Google Client

### ISSUE THREAD

**Issue by dwaite** [openid/AppAuth-JS#46]
The example apps use a public client id already registered with google. When I attempt to create my own client against the browserify app and substitute in its client id, I get a client_secret required error.

Are there instructions for how to set up a client through Google to work with this library?

#### [REQUIRED] Describe expected behavior
I would expect my client to behave similarly to the included client id, based on my guess for correct client creation parameters/

#### [REQUIRED] Actual Behavior
I get the following response
```json 
{
 "error": "invalid_request",
 "error_description": "client_secret is missing."
}
```

(page just says 'something bad happened')

#### [REQUIRED] Steps to reproduce the behavior
I create a new client at https://console.developers.google.com:
- Type: web_application (which issues it a client id and secret - client id is `465844544800-b8b08t54u74voph6f4flt1f2320q78kb.apps.googleusercontent.com` )
- Authorized Javascript Origins: http://localhost:8000
- Authorized Redirect URLs: http://localhost:8000/app/redirect.html

None of the other client types seem appropriate, as they either require a iOS bundle ID, android public key, chrome store address, and/or do not allow configuring redirect URLs at all.
#### [REQUIRED] Environment

  * AppAuth-JS version: _master_
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): _node 9.5.0, chrome, safari tech preview_  * Source code snippts (inline or JSBin)

**Comment by tikurahul** [comment]
If you want to use a `web` client id, then you need to provide a `client_secret`. Don't worry - given this is a public client the secret is not treated as a secret.

If you want to avoid using a web `client_id`. You can create an iOS client id, which does not require a `client_secret`.

**Comment by dwaite** [comment]
In the iOS case, how would you specify a http/https redirect?

**Comment by tikurahul** [comment]
If you want to use a redirect other than `localhost` then you cannot use an iOS web client. Honestly, we have had many an internal debates in Google about why we treat `Android` and `iOS` clients as special (i.e. not require a `client_secret`). 

The unfortunate answer is that you want to use a http/https redirect, just send a `client_secret` and don't worry about the rest. Sorry I don't have a better answer than that for you.

**Comment by dwaite** [comment]
Ahh!

Ok, I see - the secret-less localhost redirect is a special-case for mobile apps (which can temporarily run their own local server to receive the redirect).
