### ISSUE TITLE
[QUESTION] Can we remove the dependencies on hapi, jquery, etc?

### ISSUE THREAD

**Issue by markphillips100** [openid/AppAuth-JS#49]
I've noticed the package.json pulls in libraries that support the nodejs sample app but these dependencies leak into the npm package whether someone is using the library in a situation requiring them or not.

In addition, the xhr.ts file's Requestor class creates a dependency on some JQuery types; JQueryAjaxSettings and $.ajax.  I intend to eventually use the library in Angular 5/Ionic 3 so was hoping to not require a JQuery dependency.

Is it possible the JQueryRequestor is not used as a fallback Requestor, at least not in the core code?  I'd prefer an error that a Requestor has not been specified rather than couple to a default if possible.

**Comment by markphillips100** [comment]
Sorry, I see there's already pull requests about this very question.

**Comment by tikurahul** [comment]
We only pull `types` corresponding to the libraries you mentioned. These parts are completely swappable / replaceable depending on what you need. 

The final bundle (JS) only contains the actual parts you use. So use a bundler like `rollup` or `babel`. If you want more guidance on the how - I can add more documentation.

**Comment by markphillips100** [comment]
That's fine.  I'm using Ionic which implements its own bundling. I think it uses tree-shaking so should be good.

**Comment by tikurahul** [comment]
Marking this fixed.
