### ISSUE TITLE
Need support for openid endpoints

### ISSUE THREAD

**Issue by markphillips100** [openid/AppAuth-JS#50]
## Expected Behavior

Fetching *.well-known/openid-configuration* from the authority should return both *userinfo_endpoint* and *end_session_endpoint* URLs if available so that the consumer can inquire information about the user identity and also revoke the identity at the authority.  This would allow support for user sign-out at the authority.

#### [REQUIRED] Actual Behavior
The URLs for *userinfo_endpoint* and *end_session_endpoint* authority endpoints are not available in the type AuthorizationServiceConfiguration as optional properties.

#### [REQUIRED] Steps to reproduce the behavior
N/A

#### [REQUIRED] Environment

  * AppAuth-JS version: ________________
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): _______________________
  * Source code snippts (inline or JSBin)

**Comment by tikurahul** [comment]
Can you specify which endpoint you are using ?

**Comment by markphillips100** [comment]
I use IdentityServer 4 for my app's OpenId provider.  You can find documentation on it [here](http://docs.identityserver.io/en/release/).

There are samples available show-casing most of, if not all, the specification.
