### ISSUE TITLE
how to custom the `TokenRequest` 's header ?

### ISSUE THREAD

**Issue by geminiyellow** [openid/AppAuth-JS#58]
when i try to add some flag to the TokenRequest, 
i found there is no enter point,
and i read the code, found this:

https://github.com/openid/AppAuth-JS/blob/ce2904e3f5a4715917184244ada8903c682a23f9/src/token_request_handler.ts#L76

looks like that this library cannot custom headers,
any idea?

**Comment by tikurahul** [comment]
I think you can provide your own implementation of a `TokenRequestHandler`. We give you `BaseTokenRequestHandler` out of the box. But, if you want to add additional headers, you might want to provide your own implementation.

**Comment by geminiyellow** [comment]
thanks @tikurahul , got it.
