### ISSUE TITLE
Feature Request: Add session renewal or an iFrame AuthorizationRequestHandler implementation.

### ISSUE THREAD

**Issue by someone1** [openid/AppAuth-JS#68]
Right now, if my token provider only gives out short lived tokens (e.g. 5 minutes), I'd have to initiate a new redirect flow every time I want to renew the token to keep the user session alive. This forces me to break the user's experience and redirect/reload my app every 5 minutes! Ideally, there'd be a mechanism I could use to renew the token without initiating a redirect flow, which is all that seems to be provided from this library. I should note that I'm coming at this from the context of a SPA for which I know RFC 8252 doesn't directly apply (a SPA is not a native app, but both are public clients!) but know this library is designed to work with SPAs and even has a React example.

I guess I'd like clarification on how I can keep the user session alive without having to perform a redirect flow every time I need to refresh the session. I have coded my own implementation of an iFrame provider that implements the `AuthorizationRequestHandler` class to shoehorn this functionality into this library, but think it belong here to allow the use of `prompt=none` background/hidden refreshes for tokens where my OpenID Provider/iDP are aware of a user's session and consent status. Alternatively, could you provide an example of how we could keep a session alive with the current features provided by this library? Does implementing the [OpenID Connect Session Management Draft](http://openid.net/specs/openid-connect-session-1_0.html#CreatingUpdatingSessions) make sense for this library?

**Side note:**
[Google still recommends using the implicit flow for SPAs](https://developers.google.com/identity/protocols/OAuth2UserAgent), and in fact, you [cannot use a PKCE exchange](https://issuetracker.google.com/issues/77764959) with Google on a SPA (though [your comments](https://github.com/openid/AppAuth-JS/issues/59#issuecomment-389639290) for other issues seem to show that Google knows better!) Is this something you can clarify or maybe have addressed internally at Google?

**Comment by brockallen** [comment]
> Is this something you can clarify or maybe have addressed internally at Google?

And once they've done that, I encourage them to lead the charge at the spec committee making changes and recommendations there as well. I'd love to see a formal explanation of how code flow makes security better for SPAs. Up to now, that has not been shown.

**Comment by someone1** [comment]
I do not intend for this to become the battleground of implicit vs PKCE in SPAs. I opened a [question on Security Exchange](https://security.stackexchange.com/questions/182873/why-isnt-pkce-encouraged-for-single-page-apps) on the topic and am opened to discuss there. In the post I do mention an article that gives merit to code flows over implicit (specifically, the unintended leakage of the token in browser history) and the article itself lists other sources on the topic. I believe PKCE further improves the code flow in a SPA (well, at least enables it!) in addition to the HTTPS whitelist redirects that validates the client. If there is (currently) no demonstrable value to it, I do prefer it as a _defense-in-depth_ mechanism, if you'll give me the liberty of calling it that.

My purpose for this issue is to see if we can achieve was other libraries such as [damienbod/angular-auth-oidc-client](https://github.com/damienbod/angular-auth-oidc-client) refer to as a "[silent refresh](https://github.com/damienbod/angular-auth-oidc-client#silent-renew)" for tokens, and since I use Google OIDC tokens for authentication currently, pushing my agenda of allowing the use of PKCE in SPAs which is not currently supported by Google.

**Comment by tikurahul** [comment]
Thanks for the feature request. I am in the process of adding support for the implicit flow as I mentioned [here](https://github.com/openid/AppAuth-JS/pull/67). 

I hope that helps more clients out of the box.

**Comment by WilliamDenniss** [comment]
```
Right now, if my token provider only gives out short lived tokens (e.g. 5 minutes), I'd have to initiate a new redirect flow every time I want to renew the token to keep the user session alive. This forces me to break the user's experience and redirect/reload my app every 5 minutes! Ideally, there'd be a mechanism I could use to renew the token without initiating a redirect flow, which is all that seems to be provided from this library. 
```

Is there a reason not to use the code flow with a longer-lived token in this case? 

"Ideally, there'd be a mechanism I could use to renew the token without initiating a redirect flow" really sounds like the use-case refresh tokens solves to me.

**Comment by WilliamDenniss** [comment]
What follows is my own personal opinion. 

> [Google still recommends using the implicit flow for SPAs](https://developers.google.com/identity/protocols/OAuth2UserAgent), and in fact, you [cannot use a PKCE exchange](https://issuetracker.google.com/issues/77764959) with Google on a SPA (though [your comments](https://github.com/openid/AppAuth-JS/issues/59#issuecomment-389639290) for other issues seem to show that Google knows better!) Is this something you can clarify or maybe have addressed internally at Google?

That page pre-dates SPAs substantially, so I'm not sure if I agree with the premise of your statement ("still recommends"). I'm not aware of specific guidance for SPAs.

> And once they've done that, I encourage them to lead the charge at the spec committee making changes and recommendations there as well. I'd love to see a formal explanation of how code flow makes security better for SPAs. Up to now, that has not been shown.

Can a RFC 8252 flow work for a SPA? i.e. can the app open the browser (the actual browser with cookies, URL bar, etc), and receive a URI redirect? I've not tried to be honest. 

Conceptually the way SPAs behave feels more like a native app than a web site (no shared cookie state, no URL bar), and the code flow is required for native apps...

**Comment by someone1** [comment]
@tikurahul - That's awesome about implicit flow but that's not related to what I'm asking for here. I'd like to use the code + PKCE flow to get short-lived access tokens and silently refresh them in the background. Right now, only a redirect handler is offered, I was hoping we could add an iFrame handler so that a token could be obtained without redirecting the user who may be mid-session but in need of a refresh. I also do not intend to request a refresh token as I'd like to minimize any exposure to the user.

@WilliamDenniss - To be more explicit, the SPA is already hosted on a web server and in a web browser, so "can the app open the browser and receive a URI Redirect" isn't really applicable - or rather the answer is a roundabout yes. With implicit flows, the user loads the app and is then redirected to the AS/IDP to give permission to the app for a certain RS, and the result is redirected to a whitelisted URI for that app (remember, we are a SPA hosted on the web already) that is https protected with the access token in the url fragment. Code + PKCE works in this context as well, where instead of the access token being returned in the redirect, an authorization code is returned instead and a POST from the app containing the code + PKCE verifier to receive the access token is performed. A SPA is capable of performing both flows but the RFC is written targeted towards native apps. Although it's not formalized anywhere, there are suggestions (from comments made by @tikurahul and authors of sources I've previously linked to) that the merits of PKCE seem to apply to public clients in general, not just native apps.

The way this library is currently written, if a user had previously granted permission to a client, and the client does not have the ability to securely store a refresh token (as is the case with a SPA or any javascript based web app), then the user must be redirected to the AS/IDP before going back to the app so the client can get the token required. Any refreshes must be handled the same way mid-session. In the case of an application that wants to limit the user's exposure to security issues, I'd opt not to receive a refresh token and rely on short-lived access token instead. This way, if a user doesn't log out to kill the session/refresh token, and the app was unable to "time-out" the user due to a tab close (or some similar event), any potential leak that may have happened during the user's session would be limited to a short-lived access token, with no refresh token left active for a potential bad actor to use.

I guess my intended use-case of using code + PKCE over implicit stems from comments made by authors of Oauth related products/services that suggest we use the code + PKCE flow instead of the implicit flow for SPAs, and most point to the AppAuth libraries as the defacto implementation of the spec in order to get this done. There are some use cases for which this specific library doesn't seem well suited for but, IMHO, fall under the package's scope and isn't too far off from supporting (e.g. adding an iframe handler in addition to the existing redirect handler). In my app's use-case, users must reauthenticate on every new session to my app, but as long as they're actively using the application their session won't expire - this is achieved by using short-lived access tokens that are silently renewed as long as the app is in active use.

I hope that makes sense!

**Comment by WilliamDenniss** [comment]
> To be more explicit, the SPA is already hosted on a web server and in a web browser, so "can the app open the browser and receive a URI Redirect" isn't really applicable - or rather the answer is a roundabout yes.

So this is true when you visit the SPA *in a browser*, but it's not true if you add that SPA to your home screen and access it that way, right? In the latter case it's not being rendered in a general purpose browser (as evidenced by the lack of URI bars, and the fact if you open a link outside of the SPA, it will open in the browser app), but rather it's treated more like a native app.

Are you solving for both environments, or just the former? If the former, does the distinction of "SPA" change anything, i.e. can you just say "website" instead of "SPA" and everything would be the same?

> I was hoping we could add an iFrame handler so that a token could be obtained without redirecting the user who may be mid-session but in need of a refresh

Is this "iFrame handler" defined in an OAuth spec? If not, then it's likely out of scope for AppAuth.

As you've found, the implicit flow requires a full-page redirect to get a new token. So would the code flow, if the refresh token was similarly time-bound. So really, if you want to provide a nice user experience to such users, longer-lived tokens are needed (regardless of "flow").

**Comment by brockallen** [comment]
> Is this "iFrame handler" defined in an OAuth spec? If not, then it's likely out of scope for AppAuth.

OAuth2 does not preclude it, and OIDC specifically adds prompt=none to formalize it.

> Conceptually the way SPAs behave feels more like a native app than a web site (no shared cookie state, no URL bar), and the code flow is required for native apps...

Implicit is designed to limit the ability to renew access tokens to the user's browser session. Code flow leads to refresh tokens, which allows for renewing access tokens beyond that browser session (given that it's a public client). This is the main "pandora's box" security concern for code flow in the browser, IMO. I'd love for the spec committees to get involved with addressing this. I posted a few months ago to the list on this exact topic.

**Comment by tikurahul** [comment]
@someone1 You are correct. This library is meant to solve the low level plumbing meant to make the kind of flows you are talking about easier. So you could pass an instance of `LocationLike` that belonged to an iframe. Such an implementation would go beyond the scope of this library like you have identified. 
The `RedirectRequestHandler` is very versatile. 

I am not sure I understand what you mean when you say Google does not support web clients. It does. `AppAuth-JS` will get out of the box PKCE support soon. I just wanted to provide similar interfaces which can help with substitution around the how of generating `sha256`s. I just have not gotten to it yet. There are a couple of forks that have also added this on top of the existing library. The `AppAuth-JS` implementation is newer than its corresponding iOS and Android implementations. I don't have higher level APIs yet, but they too are coming. Having used this library in a number of projects now, I have an API that I am happy with.

---

I also need to reiterate that this library will not and need not support every OAuth2 and OIDC RFC. I don't have *any* intention of doing so. If there is a feature that's missing, feel free to fork the library and add that feature. This library however will make that process hopefully easier. This is a volunteer run, 20% project like the rest of `AppAuth-*` projects.

**Comment by someone1** [comment]
@tikurahul First and foremost, I am truly appreciative and grateful of the fact that you are supporting this project the way you are. 

RE Google & PKCE - You cannot use PKCE on anything but with iOS or Android application types. If you try and use PKCE with Web application type, it will expect the `client_secret` on the code/token exchange step. This is when I use the [Credentials Console](https://console.developers.google.com/apis/credentials/) to create a new oauth client and select the "Web application" Application type. This is the only application type that allows me to enter HTTPS redirect URIs which is what would be required for a browser-based PKCE flow. I opened support cases with Developer support and was told to open the [issue I linked to](https://issuetracker.google.com/issues/77764959) previously - were you able to get this working with the web application type, and if so, how?

**Comment by tikurahul** [comment]
Yes, that is a distinction Google makes when you choose the web client. But the `client_secret` in question is just a secret in name only. Google knows that web clients are `public` clients and that they cannot keep any secrets. Nothing in the protocol is predicated on the `client_secret` being a secret. I suggest that you just send `client_secret`.

All I can say is that, it’s unfortunate that Google makes this distinction based on the client type.

**Comment by xBurnsed** [comment]
@tikurahul 6 years has passed and I have came across this comment of yours today.
In the official [documentation](https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow), the implicit flow is still suggested way to proceed, and this not a recommended flow anymore as of today.

For "web application" types, we are still forced to send the client_secret when attempting to exhance the code for tokens, but by reading your message, you are really suggesting that we should be explosing the "client_secret" in our client because it is not really a secret? This is really confusing to be honest.

What is it used for then? I don't see anywhere in the docs that mention that exposing the client_secret in the browser is safe

Could you give more insight into this?

Thanks!

**Comment by jakefeasel** [comment]
@xBurnsed  You might want to consider using the [AppAuthHelper](/forgerock/AppAuthHelper) project, which is an extension of the AppAuth-JS library specifically designed to make it easier to implement for SPA clients. Token renewal via the refresh token grant is a supported option with it (especially useful in a third-party context when idp session cookies may not be available to an iframe).

Full disclosure- I built the majority of this extension. Feel free to ping me if you have questions.

**Comment by zjteachen** [comment]
@xBurnsed I am also really surprised at the suggestion of leaking the client_secret. To my understanding leaking this would allow any arbitrary impersonation attack through using the id and secret with authorization code flow without PKCE, as to my understanding GCP does not allow enabling/disabling of specific grants.

In addition GCP documentation establishes a the web application client type as a client capable of keeping secrets. It doesn't make any suggestion that web applications are public clients (at least I could find)
