### ISSUE TITLE
example app should fetch all resources from https:// and pass event to callback functions

### ISSUE THREAD

**Issue by dholth** [openid/AppAuth-JS#73]
There are a couple of small mistakes in `app/index.html`. It should fetch all its resources from https:// (the Roboto font) and it calls `event.preventDefault()` without passing `event` to its callback functions.

Thanks!

**Comment by tikurahul** [comment]
The example is just _an_ example. 
Also, I am not using `event` at all in my callback functions.

**Comment by dholth** [comment]
There: https://github.com/openid/AppAuth-JS/blob/master/app/index.html#L57

**Comment by tikurahul** [comment]
Thanks, this should fix it.
https://github.com/openid/AppAuth-JS/pull/82
