### ISSUE TITLE
Drop TextEncoder requirement

### ISSUE THREAD

**Issue by someone1** [openid/AppAuth-JS#83]
The need for TextEncoder is limited and it is [not supported](https://caniuse.com/#search=TextEncoder) (without expensive polyfills) on IE or Edge.

It is easily replaced as follows:

```ts
// modified from source: http://stackoverflow.com/a/11058858
export function str2ab(str: string) {
  const buf = new ArrayBuffer(str.length);
  const bufView = new Uint8Array(buf);
  for (let i = 0; i < str.length; i++) {
    bufView[i] = str.charCodeAt(i);
  }
  return buf;
}

crypto.subtle.digest('SHA-256', str2ab(code))

**Comment by someone1** [comment]
Yeah sure, I'll get one to you shortly.

**Comment by tikurahul** [comment]
Fixed by https://github.com/openid/AppAuth-JS/pull/87

**Comment by jurepurgar** [comment]
@tikurahul any ETA on when this will make it to the npmjs?

**Comment by tikurahul** [comment]
Yes. I forgot about that. I am back from vacation on Mon. I will publish it then.

**Comment by jurepurgar** [comment]
OK great. Let us know when it is available :)

**Comment by tikurahul** [comment]
Sorry about the delay. Have been swamped with a lot of other things.

AppAuth-JS 1.1.2 is now live.
https://www.npmjs.com/package/@openid/appauth

Now uses TypeScript 3.2.1.
