### ISSUE TITLE
Token request is blocked by client_secret requirement 

### ISSUE THREAD

**Issue by alxmiron** [openid/AppAuth-JS#91]
I tested an example browser app from this repo and it works fine. But if I test it with my `clientId` I get an error "client_secret is missing" on last POST `https://oauth2.googleapis.com/token` request (fetching refresh token)

Am I missing something in oauth client configuration in google console? I suppose some notes should be added to readme

  * AppAuth-JS version: 1.1.1
  * AppAuth-JS Environment: browser

**Comment by nelsonwellswku** [comment]
@tikurahul - That was the issue. Thanks for the help.

**Comment by Murukaen** [comment]
Is this the recommended solution even when using the library in production for a desktop native app?

**Comment by tikurahul** [comment]
Using both an iOS or Web client ID is okay. For all public clients the client secrets are not treated as real secrets.

**Comment by Murukaen** [comment]
Thanks for the answer @tikurahul. I want to mention that, while the ios app works, a web app fails with the client_secret requirement.
