### ISSUE TITLE
configurable "usehash" while parsing queryParams in RedirectRequestHandler

### ISSUE THREAD

**Issue by anandvnath** [openid/AppAuth-JS#92]
## Expected Behavior
Currently in RedirectRequestHandler.completeAuthorizationRequest, it is assumed that useHash is true for parsing the queryParams. In my case, the response has no hash value. So parsing query params always fails.

Line# 100: let queryParams = this.utils.parse(this.locationLike, true /* use hash */);

#### [REQUIRED] Describe expected behavior
useHash should be configurable.

## Describe the problem
Unable to complete auth request using RedirectRequestHandler.completeAuthorizationRequest

#### [REQUIRED] Actual Behavior
useHash should be configurable.

#### [REQUIRED] Steps to reproduce the behavior
Do an auth where redirect response does not have a hash.

#### [REQUIRED] Environment
Any open id configuration should do, I am not sure what case hash is null.

  * AppAuth-JS version: 1.1.1
  * AppAuth-JS Environment (Node, Browser (UserAgent), ...): Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
  * Source code snippts (inline or JSBin)

**Comment by tikurahul** [comment]
I believe `RedirectRequestHandler` can already take in a custom query string parser. You pass it in a constructor and it’s currently set to `BasicQueryStringUtils`. You could extend the class and always ignore `useHash` if that’s your intention.

**Comment by anandvnath** [comment]
Yes. That will work.

Thanks
